### ISSUE TITLE
onKeyDown/onKeydown is not correctly passed to the PowerSelect component

### ISSUE THREAD

**Issue by jmmorganMSTS** [ember-bootstrap/ember-bootstrap-power-select#344]
The documentation for ember-power-select defines an `onKeydown` argument. ember-bootstrap-power-select is instead [passing through an `onKeyDown` argument](https://github.com/ember-bootstrap/ember-bootstrap-power-select/blob/master/addon/components/bs-form/element/control/power-select.hbs#L34).

The case mismatch makes it difficult to set the keydown handler on power-selects.

**Comment by jelhan** [comment]
Thanks a lot for reporting. PR fixing the typo is very welcome.
